# Generated by Django 5.0.6 on 2024-06-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_worklog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='worklog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
